//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oblig_csharp_2021_frontend_win.RecursosGraficos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextosEnPantalla {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextosEnPantalla() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("oblig_csharp_2021_frontend_win.RecursosGraficos.TextosEnPantalla", typeof(TextosEnPantalla).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año de Creacion.
        /// </summary>
        internal static string ACreacion {
            get {
                return ResourceManager.GetString("ACreacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Album ID.
        /// </summary>
        internal static string AlbumID {
            get {
                return ResourceManager.GetString("AlbumID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Año de Separacion.
        /// </summary>
        internal static string ASeparacion {
            get {
                return ResourceManager.GetString("ASeparacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banda.
        /// </summary>
        internal static string Banda {
            get {
                return ResourceManager.GetString("Banda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Banda ID.
        /// </summary>
        internal static string BandaID {
            get {
                return ResourceManager.GetString("BandaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pertenece a la Banda.
        /// </summary>
        internal static string BandaIDIntegrante {
            get {
                return ResourceManager.GetString("BandaIDIntegrante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancion ID.
        /// </summary>
        internal static string CancionID {
            get {
                return ResourceManager.GetString("CancionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. Albumes.
        /// </summary>
        internal static string CantAlbumes {
            get {
                return ResourceManager.GetString("CantAlbumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantante Principal.
        /// </summary>
        internal static string CantantePrin {
            get {
                return ResourceManager.GetString("CantantePrin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantante Principal.
        /// </summary>
        internal static string CantantePrincipal {
            get {
                return ResourceManager.GetString("CantantePrincipal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. Canciones.
        /// </summary>
        internal static string CantCanciones {
            get {
                return ResourceManager.GetString("CantCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cant. Integrantes.
        /// </summary>
        internal static string CantIntegs {
            get {
                return ResourceManager.GetString("CantIntegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recargaron los datos correctamente.
        /// </summary>
        internal static string CargaCorrecta {
            get {
                return ResourceManager.GetString("CargaCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion, se elimino.
        /// </summary>
        internal static string ConfDelete {
            get {
                return ResourceManager.GetString("ConfDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han cargado los datos iniciales correctamente.
        /// </summary>
        internal static string ConfInicializar {
            get {
                return ResourceManager.GetString("ConfInicializar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion, se inserto.
        /// </summary>
        internal static string ConfInsert {
            get {
                return ResourceManager.GetString("ConfInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirme eliminacion.
        /// </summary>
        internal static string ConfirmarEliminacion {
            get {
                return ResourceManager.GetString("ConfirmarEliminacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Eliminacion.
        /// </summary>
        internal static string ConfirmarEliminacionBTN {
            get {
                return ResourceManager.GetString("ConfirmarEliminacionBTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Ingreso.
        /// </summary>
        internal static string ConfirmarIngreso {
            get {
                return ResourceManager.GetString("ConfirmarIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para cargar un nuevo album.
        /// </summary>
        internal static string ConfirmarIngresoAlbum {
            get {
                return ResourceManager.GetString("ConfirmarIngresoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para cargar una nueva banda.
        /// </summary>
        internal static string ConfirmarIngresoBanda {
            get {
                return ResourceManager.GetString("ConfirmarIngresoBanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para cargar una nueva cancion.
        /// </summary>
        internal static string ConfirmarIngresoCancion {
            get {
                return ResourceManager.GetString("ConfirmarIngresoCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilito el campo para cargar un nuevo genero musical.
        /// </summary>
        internal static string ConfirmarIngresoGenMusical {
            get {
                return ResourceManager.GetString("ConfirmarIngresoGenMusical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para cargar un nuevo cantante.
        /// </summary>
        internal static string ConfirmarIngresoIntegrante {
            get {
                return ResourceManager.GetString("ConfirmarIngresoIntegrante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Inizializar.
        /// </summary>
        internal static string ConfirmarInicializar {
            get {
                return ResourceManager.GetString("ConfirmarInicializar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Limpieza.
        /// </summary>
        internal static string ConfirmarLimpieza {
            get {
                return ResourceManager.GetString("ConfirmarLimpieza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han borrado los datos correctamente en la base de datos.
        /// </summary>
        internal static string ConfLimpieza {
            get {
                return ResourceManager.GetString("ConfLimpieza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Modificación.
        /// </summary>
        internal static string ConfModif {
            get {
                return ResourceManager.GetString("ConfModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmacion, se modifico.
        /// </summary>
        internal static string ConfUpdate {
            get {
                return ResourceManager.GetString("ConfUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a testData.
        /// </summary>
        internal static string Dato {
            get {
                return ResourceManager.GetString("Dato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url imagen de cover.
        /// </summary>
        internal static string DatoCancion {
            get {
                return ResourceManager.GetString("DatoCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url imagen de cantante.
        /// </summary>
        internal static string DatoIntegrante {
            get {
                return ResourceManager.GetString("DatoIntegrante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos recuperados correctamente del Album de ID:: .
        /// </summary>
        internal static string DatosRecAlbumOk {
            get {
                return ResourceManager.GetString("DatosRecAlbumOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos *NO* recuperados correctamente de la Banda de ID:: .
        /// </summary>
        internal static string DatosRecBandaNOTok {
            get {
                return ResourceManager.GetString("DatosRecBandaNOTok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos recuperados correctamente de la Banda de ID:: .
        /// </summary>
        internal static string DatosRecBandaOk {
            get {
                return ResourceManager.GetString("DatosRecBandaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos recuperados correctamente de la Cancion de ID:: .
        /// </summary>
        internal static string DatosRecCancionOk {
            get {
                return ResourceManager.GetString("DatosRecCancionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos recuperados correctamente de Genero Musical de ID::.
        /// </summary>
        internal static string DatosRecGeneroMusOk {
            get {
                return ResourceManager.GetString("DatosRecGeneroMusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos recuperados correctamente del Cantante de ID::.
        /// </summary>
        internal static string DatosRecIntegranteOk {
            get {
                return ResourceManager.GetString("DatosRecIntegranteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Duración.
        /// </summary>
        internal static string Duracion {
            get {
                return ResourceManager.GetString("Duracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error:: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error el intentar insertar.
        /// </summary>
        internal static string ErrorIngreso {
            get {
                return ResourceManager.GetString("ErrorIngreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo completar el proceso por algun motivo.
        /// </summary>
        internal static string ErrorProcedimiento {
            get {
                return ResourceManager.GetString("ErrorProcedimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de Nacimeinto.
        /// </summary>
        internal static string FechaNacimiento {
            get {
                return ResourceManager.GetString("FechaNacimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero Musical ID.
        /// </summary>
        internal static string GeneroMusicalID {
            get {
                return ResourceManager.GetString("GeneroMusicalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Genero Musical.
        /// </summary>
        internal static string GenMus {
            get {
                return ResourceManager.GetString("GenMus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Albumes.
        /// </summary>
        internal static string GenMusCantAlbumes {
            get {
                return ResourceManager.GetString("GenMusCantAlbumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Bandas.
        /// </summary>
        internal static string GenMusCantBandas {
            get {
                return ResourceManager.GetString("GenMusCantBandas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de Canciones.
        /// </summary>
        internal static string GenMusCantCanciones {
            get {
                return ResourceManager.GetString("GenMusCantCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Info:: .
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el ID de un Album para ver sus canciones.
        /// </summary>
        internal static string IngreseAlbumIDParaCanciones {
            get {
                return ResourceManager.GetString("IngreseAlbumIDParaCanciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el ID de una Banda para ver sus albumes.
        /// </summary>
        internal static string IngreseBandaIDParaAlbumes {
            get {
                return ResourceManager.GetString("IngreseBandaIDParaAlbumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el ID de una Banda para ver sus integrantes.
        /// </summary>
        internal static string IngreseBandaIDParaIntegrantes {
            get {
                return ResourceManager.GetString("IngreseBandaIDParaIntegrantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe ingresar un ID valido para poder buscar.
        /// </summary>
        internal static string IngreseIDParaBuscar {
            get {
                return ResourceManager.GetString("IngreseIDParaBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foto de Integrante.
        /// </summary>
        internal static string IntegranteDato {
            get {
                return ResourceManager.GetString("IntegranteDato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Integrante ID.
        /// </summary>
        internal static string IntegranteID {
            get {
                return ResourceManager.GetString("IntegranteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Persona ID.
        /// </summary>
        internal static string PersonaID {
            get {
                return ResourceManager.GetString("PersonaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para que pueda modificar los datos basicos del Album de ID:: .
        /// </summary>
        internal static string PuedeModificarAlbum {
            get {
                return ResourceManager.GetString("PuedeModificarAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para que pueda modificar los datos basicos de la Banda de ID:: .
        /// </summary>
        internal static string PuedeModificarBanda {
            get {
                return ResourceManager.GetString("PuedeModificarBanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para que pueda modificar los datos basicos de la Cancion de ID::.
        /// </summary>
        internal static string PuedeModificarCancion {
            get {
                return ResourceManager.GetString("PuedeModificarCancion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilito el campo para que pueda modificar el dato del Genero Musical de ID::.
        /// </summary>
        internal static string PuedeModificarGenMusical {
            get {
                return ResourceManager.GetString("PuedeModificarGenMusical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se habilitaron los campos para que pueda modificar los datos basicos del Cantante de ID::.
        /// </summary>
        internal static string PuedeModificarIntegrante {
            get {
                return ResourceManager.GetString("PuedeModificarIntegrante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recargando....
        /// </summary>
        internal static string Recargando {
            get {
                return ResourceManager.GetString("Recargando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Success:: .
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning:: .
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
